
  File "C:/Users/localadmin_mifrey/Desktop/PJSem_S/nichtLinear/evaluate_connect_Devices.py", line 237, in <module>
    check_AWG()

  File "C:/Users/localadmin_mifrey/Desktop/PJSem_S/nichtLinear/evaluate_connect_Devices.py", line 138, in check_AWG
    b = AWG.query("SYSTem:ERRor?")

  File "D:\Programme\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\pyvisa\resources\messagebased.py", line 407, in query
    return self.read()

  File "D:\Programme\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\pyvisa\resources\messagebased.py", line 332, in read
    message = self.read_raw().decode(enco)

  File "D:\Programme\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\pyvisa\resources\messagebased.py", line 306, in read_raw
    chunk, status = self.visalib.read(self.session, size)

  File "D:\Programme\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1582, in read
    ret = library.viRead(session, buffer, count, byref(return_count))

  File "D:\Programme\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)

VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.