Abbruch im Bewertungstool mit

bei Durchlauf 4 für sigma = 0.2
folgende Messung gneuaso





    quality = signal_evaluate(data_directory + 'Uout_measured_' + id + '.csv', data_directory + 'quality_' + id + '.csv')

  File "C:\Users\localadmin_mifrey\Desktop\PJSem_S\nichtLinear\helpers\signal_evaluation.py", line 33, in signal_evaluate
    Startindex=Startindex)

  File "C:\Users\localadmin_mifrey\Desktop\PJSem_S\nichtLinear\tools\singlesine_SineRef.py", line 106, in SineRef
    dataPointsRef = opt[0] * np.append(np.append(np.zeros(abs(lagDiff)),np.sin(2*np.pi*fBB*t+opt[1])),np.zeros(PointsPerPeriod-abs(lagDiff)-len(pulse)))

UnboundLocalError: local variable 'opt' referenced before assignment